export const rows = [
  "DOT_NUMBER",
  "LEGAL_NAME",
  "DBA_NAME",
  "CARRIER_OPERATION",
  "HM_FLAG",
  "PC_FLAG",
  "PHY_STREET",
  "PHY_CITY",
  "PHY_STATE",
  "PHY_ZIP",
  "PHY_COUNTRY",
  "MAILING_STREET",
  "MAILING_CITY",
  "MAILING_STATE",
  "MAILING_ZIP",
  "MAILING_COUNTRY",
  "TELEPHONE",
  "FAX",
  "EMAIL_ADDRESS",
  "MCS150_DATE",
  "MCS150_MILEAGE",
  "MCS150_MILEAGE_YEAR",
  "ADD_DATE",
  "OIC_STATE",
  "NBR_POWER_UNIT",
  "DRIVER_TOTAL"
]
export const data = [{
  "DOT_NUMBER": "DOT_NUMBER",
  "LEGAL_NAME": "LEGAL_NAME",
  "DBA_NAME": "DBA_NAME",
  "CARRIER_OPERATION": "CARRIER_OPERATION",
  "HM_FLAG": "HM_FLAG",
  "PC_FLAG": "PC_FLAG",
  "PHY_STREET": "PHY_STREET",
  "PHY_CITY": "PHY_CITY",
  "PHY_STATE": "PHY_STATE",
  "PHY_ZIP": "PHY_ZIP",
  "PHY_COUNTRY": "PHY_COUNTRY",
  "MAILING_STREET": "MAILING_STREET",
  "MAILING_CITY": "MAILING_CITY",
  "MAILING_STATE": "MAILING_STATE",
  "MAILING_ZIP": "MAILING_ZIP",
  "MAILING_COUNTRY": "MAILING_COUNTRY",
  "TELEPHONE": "TELEPHONE",
  "FAX": "FAX",
  "EMAIL_ADDRESS": "EMAIL_ADDRESS",
  "MCS150_DATE": "MCS150_DATE",
  "MCS150_MILEAGE": "MCS150_MILEAGE",
  "MCS150_MILEAGE_YEAR": "MCS150_MILEAGE_YEAR",
  "ADD_DATE": "ADD_DATE",
  "OIC_STATE": "OIC_STATE",
  "NBR_POWER_UNIT": "NBR_POWER_UNIT",
  "DRIVER_TOTAL": "DRIVER_TOTAL",
}]

export const SSD = {
  id:"765afdtsbjh",
  name: "Effects of Social Media",
  status: "complete", // or "in-progress"
  responded: 20,
  description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clitaLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet",
  answers: [
      {
          questionText:"Who is the thiccest of them all?",
          questionId:"ahsgd8217",
          questionType:"choice",
          choiceId:"1d82ahsg17",
          ansText:"",
      },
      {
          questionText:"Who is the fastest of them all?",
          questionId:"ahsgd8217",
          questionType:"choice",
          choiceId:"2ahsd82g17",
          ansText:"",
      },
      {
          questionText:"Who is the fairest of them all?",
          questionId:"gd8ahs217",
          questionType:"text-field",
          choiceId:null,
          ansText:"Lorem",
      },
      {
          questionText:"Who is the dumbest of them all?",
          questionId:"gd8ahs217",
          questionType:"text-field",
          choiceId:null,
          ansText:"Ipsum",
      },

  ]
}